### PR TITLE
feat: remove anklet tracker functionality

### PR DESCRIPTION
**Pull request by mafewtm**
## Description

Removes the unused and old anklet tracker functionality

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Comment by jnccloud** [comment]
This functionality was actually pretty useful in RP situations with someone on house arrest, someone in witness protection, etc. Any reason to remove it besides it not appearing useful to you?

**Comment by mafewtm** [comment]
Most servers don't use this as no one is staying online for 4+ hours just to sit in their house or for fake witness protection. While, in a perfect world this is a great idea, in reality it really is not. Regardless, we will probably be making a separate resource for this functionality.

**Comment by jnccloud** [comment]
A separate resource would be ideal then because I can still see scenarios where this can, and has been used... none of them require someone staying in their house for 4+ hours either. Just used that as an easy example. Its definitely something I've seen utilized in servers with FIB or detectives.

**Comment by Manason** [comment]
I would create the separate resource before removing it from this one.

**Comment by mafewtm** [comment]
I don't think it should be a thing we support but if that's yall want then someone can do it down the road

**Pull request closed without merging**
